module.exports = {
  someSidebar: {
    "Home": ["introduction", "about", "in-dev"],
    "Atomic Structure": [
      "atomic-structure/classroom-language",
      "atomic-structure/language-structure",
      "atomic-structure/vocabulary-practice-tips",
      "atomic-structure/glossary",
      {"The structure of an atom": [
      "atomic-structure/the-structure-of-an-atom/reading",
      "atomic-structure/the-structure-of-an-atom/practice-exercises"]},
      {"Electron shell of an atom": [
        "atomic-structure/electron-shell-of-an-atom/reading",
        "atomic-structure/electron-shell-of-an-atom/practice-exercises"]},
      {"Mass spectrometry": [
        "atomic-structure/mass-spectrometry/reading",
        "atomic-structure/mass-spectrometry/practice-exercises"]},
      "atomic-structure/bloom-taxonomy",
      "atomic-structure/video-lesson",
      "atomic-structure/students-self-study",
      "atomic-structure/teaching-method",
    ],
    Periodicity: [
      "periodicity/classroom-language",
      "periodicity/language-structure",
      "periodicity/vocabulary-practice-tips",
      "periodicity/glossary",
      "periodicity/reading",
      "periodicity/practice-exercises",
      "periodicity/bloom-taxonomy",
      "periodicity/video-lesson",
      "periodicity/students-self-study",
      "periodicity/teaching-method",
    ],
    Bonding: [
      "bonding/classroom-language",
      "bonding/language-structure",
      "bonding/vocabulary-practice-tips",
      "bonding/glossary",
      "bonding/reading",
      "bonding/practice-exercises",
      "bonding/bloom-taxonomy",
      "bonding/video-lesson",
      "bonding/students-self-study",
      "bonding/teaching-method",
    ],
    Energetics: [
      "energetics/classroom-language",
      "energetics/language-structure",
      "energetics/vocabulary-practice-tips",
      "energetics/glossary",
      "energetics/reading",
      "energetics/practice-exercises",
      "energetics/bloom-taxonomy",
      "energetics/video-lesson",
      "energetics/students-self-study",
      "energetics/teaching-method",
    ],
    Kinetics: [
      "kinetics/classroom-language",
      "kinetics/language-structure",
      "kinetics/vocabulary-practice-tips",
      "kinetics/glossary",
      "kinetics/reading",
      "kinetics/practice-exercises",
      "kinetics/bloom-taxonomy",
      "kinetics/video-lesson",
      "kinetics/students-self-study",
      "kinetics/teaching-method",
    ],
  },
};
